-- Copia y pega esto en el "SQL Editor" de Supabase para crear la tabla

create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text not null,
  product text not null,
  cost numeric not null,
  price numeric not null,
  paid_amount numeric default 0,
  status text not null,
  date text default to_char(now(), 'YYYY-MM-DD')
);
